install.packages("readxl")
install.packages("tidyverse")
install.packages("ggplot2")
install.packages("plotly")
install.packages("pastecs")
install.packages("fdth")
install.packages("PASWR2")
install.packages("descr")
install.packages("lmtest")
install.packages("dplyr")
install.packages("readr")

library(readxl)
library(tidyverse)
library(ggplot2)
library(plotly)
library(pastecs)
library (fdth)
library(PASWR2)
library(descr)
library(lmtest)
library(dplyr)
library(readr)

life_expectancy <- read_csv("../baseDeDatos/lifeExpectancy.csv") 
View(life_expectancy)
